document.write("<div>")
document.write("<h1>Расписание</h1>")
document.write("<p><span>8.00-9.35</span> Разработка мобильных приложений (лаб)доц Завозкин С.Ю.,ауд. 2130а</p>")
document.write("<p><span>9.45-11.20</span> Базы данных (лаб)доц. Завозкин С.Ю., ауд. 2130а</p>")
document.write("<p><span>11.45-13.20</span> Программная инженерия (лаб)асс. Илькевич В.В.,ауд. 2220</p>")
document.write("</div>")